[build]
  base = "."
  command = "./server/ && npm run build:prod && cd .."
  publish = "client/main"

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200

[context.production]
  command = "./server/ && npm run build:prod && cd .."