[build]
  base = "."
  command = "./index.js && npm run build:prod"
  publish = "client/main"

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200

[context.production]
  command = "./index.js && npm run build:prod"