[build]
  base = "."
  command = "./server/index.js && cd .. && npm run build:prod"
  publish = "client/main"

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200

[context.production]
  command = "./server/index.js && cd .. && npm run build:prod"