[build]
  base = "."
  publish = "client/main"
  command = "cd /opt/build/repo/server && npm run build:prod"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200

[context.production]
  command = "cd /opt/build/repo/server && npm run build:prod"

[context.production.processing]
  skip_processing = false